name: Handle labels

runs:
  using: composite
  steps:
    - uses: dessant/label-actions@v2
      with:
        # TODO: for now we should keep the config file in the each repo
        # We should do something to keep only a single config file
        config-path: .github/labels.yml