name: Prepare

runs:
  using: composite
  steps:
    - if: ${{ github.event.pull_request }}
      uses: DevExpress/testcafe-build-system/actions/checkout-pr@main
    
    - if: ${{ !github.event.pull_request }}
      uses: actions/checkout@v3
