name: Build NPM package

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        npm i --legacy-peer-deps
        npm run lint --if-present
        npm run build --if-present
        npm pack --pack-destination .builds
          
    - uses: actions/upload-artifact@v3
      with:
        name: npm
        path: |
          .builds/
          package-lock.json