name: "Detect build scripts"

outputs:
  name:
    value: ${{ steps.detect_scripts.outputs.name }}
  version:
    value: ${{ steps.detect_scripts.outputs.version }}
  scripts:
    value: ${{ steps.detect_scripts.outputs.scripts }}

runs:
  using: "composite"
  steps: 
    - id: detect_scripts
      uses: actions/github-script@v3
      with: 
        script: |
          const path = require('path');

          function joinPath (...args) {
            return path.join('${{ github.workspace }}', ...args);
          }

          const packageInfoPath = joinPath('package.json');
          const packageInfo     = require(packageInfoPath);

          core.setOutput('name', packageInfo.name);
          core.setOutput('version', packageInfo.version);
          core.setOutput('scripts', Object.keys(packageInfo.scripts).filter(script => script.startsWith('build')))

          const workspaces = packageInfo.workspaces || [];

          const workspacesData = JSON.stringify(workspaces.map(w => { 
            const workspaceInfo = require(joinPath(w, 'package.json'));

            return { path: w, name: workspaceInfo.name, version: workspaceInfo.version }; 
          }));

          console.log(workspacesData);
          
          core.setOutput('workspaces', workspacesData);
