name: Log In NPM

inputs:
  registry:
    required: false
    default: 'registry.npmjs.org'
  protocol:
    required: false
    default: 'https'
  token:
    required: false

runs:
  using: composite
  env: 
  steps:
    - shell: bash
      run: |
        npm config set registry "${{ inputs.protocol || 'https' }}://${{ inputs.registry || 'registry.npmjs.org' }}/"
        npm config set "//${{ inputs.registry || 'registry.npmjs.org' }}/:_authToken" "${{ inputs.token || env.NPM_TOKEN || env.NODE_AUTH_TOKEN }}"
