name: "Detect build scripts"

outputs:
  scripts:
    value: ${{ steps.detect_scripts.outputs.scripts }}

runs:
  using: "composite"
  steps: 
    - id: detect_scripts
      uses: actions/github-script@v3
      with: 
        script: |
          console.log(321);
          
          const path = require('path');

          const packageInfoPath = path.join('${{ github.workspace }}', 'package.json');

          core.setOutput("scripts", Object.keys(require(packageInfoPath).scripts).filter(script => script.startsWith('build')))
