name: "Detect build scripts"

outputs:
  scripts:
    value: ""

runs:
  using: "composite"
  steps: 
    - using: actions/github-script@v3
      with: 
        script: |
          core.setOutput("scripts", Object.keys(require('./package.json').scripts).filter(script => script.startsWith('build')))
