name: "Detect build scripts"

outputs:
  scripts:
    value: ""

runs:
  using: "composite"
  steps: 
    - uses: actions/github-script@v3
      with: 
        script: |
          const path = require('path');

          const packageInfoPath = path.join(context.github.workspace, 'package.json');

          core.setOutput("scripts", Object.keys(require(packageInfoPath).scripts).filter(script => script.startsWith('build')))
