name: Test NPM

inputs:
  task:
    default: test

runs:
  using: composite
  steps:
    - uses: DevExpress/testcafe-build-system/actions/load-artifacts-npm@main
        
    - shell: bash
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - uses: actions/cache@v2
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - shell: bash
      run: npm ci --legacy-peer-deps

    - shell: bash
      run: npm run ${{ inputs.task }}