name: Read matrix status

outputs:
  status: 
    description: "Matrix status"
    value: ${{ steps.matrix-status.outputs.status }}

runs:
  using: composite
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: matrix-status

    - name: Read matrix status
      id: matrix-status
      shell: bash
      run: echo status=$([ $(grep -h -v "success" matrix-status-*.txt | wc -l) -eq 0 ] && echo "success" || echo "failure") >> "$GITHUB_OUTPUT"