name: Set status

inputs:
  status:
    required: true

runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.ACTIVE_TOKEN }}
        script: |
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.payload.inputs.sha,
            context: context.workflow,
            state: '${{ inputs.status }}',
            target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}${{inputs.artifacts-path}}`
          });