name: Publish with publish-please

runs:
  using: composite
  steps:
    - uses: DevExpress/testcafe-build-system/actions/prepare@main

    - uses: DevExpress/testcafe-build-system/actions/build@main
    
    - shell: bash
      run: npm install && git status
      
    - shell: bash
      run: npx publish-please
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
