name: Publish with publish-please

inputs:
  token:
    required: false
    
runs:
  using: composite
  steps:
    - uses: DevExpress/testcafe-build-system/actions/prepare@main

    - uses: DevExpress/testcafe-build-system/actions/build@main
    
    - shell: bash
      run: npm install && git status && git diff
      
    - uses: actions/github-script@v6
      with:
        script: console.log((${{inputs.token}}).slice(0,6))
        
    - shell: bash
      run: npx publish-please
      env:
          NODE_AUTH_TOKEN: ${{ inputs.token || env.NODE_AUTH_TOKEN }}
