name: Publish with publish-please

inputs:
  registry:
    required: false
  protocol:
    required: false
  token:
    required: false
  owner:
    required: false
    
runs:
  using: composite
  steps:
    - uses: DevExpress/testcafe-build-system/actions/prepare@main

    - uses: DevExpress/testcafe-build-system/actions/build@main

    - uses: DevExpress/testcafe-build-system/actions/login-npm@main
      with:
        registry: ${{ inputs.registry }}
        protocol: ${{ inputs.protocol }}
        token: ${{ inputs.token }}

    # TODO: do something with "npm install" changing package-lock.json
    - shell: bash
      run: git checkout -- package-lock.json

    - shell: bash
      run: npx publish-please
