name: Publish with publish-please

inputs:
  registry:
    required: false
    default: 'registry.npmjs.org'
  token:
    required: false
    
runs:
  using: composite
  steps:
    - uses: DevExpress/testcafe-build-system/actions/prepare@main

    - uses: DevExpress/testcafe-build-system/actions/build@main

    - shell: bash
      run: npm config set "//${{ inputs.registry }}/:_authToken" "${{ inputs.token || env.NPM_TOKEN || env.NODE_AUTH_TOKEN }} "

    # TODO: do something with "npm install" changing package-lock.json
    - shell: bash
      run: git checkout -- package-lock.json

    - shell: bash
      run: npx publish-please
