name: Detect PR title

outputs: 
  title:
    value: ${{ steps.detect-title.outputs.title }}

runs:
  using: composite
  steps:
    - id: detect-title
      uses: actions/github-script@v6
      if: ${{ github.event.pull_request }}
      with:
        script: |
          const event = require(process.env.GITHUB_EVENT_PATH);
          
          const repo   = event.repository.name;
          const owner  = event.repository.owner.login;
          const number = event.pull_request.number;

          const pullRequest = await github.rest.pulls.get({ owner, repo, pull_number: number });

          core.setOutput('title', pullRequest.title);