name: Detect PR title

outputs: 
  type:
    title: ${{ steps.detect-title.outputs.type }}

runs:
  using: composite
  steps:
    - id: detect-title
      uses: actions/github-script@v6
      if: ${{ github.event.pull_request }}
      with:
        script: |
          const event = require(process.env.GITHUB_EVENT_PATH);

          core.setOutput('title', event.pull_request.title);