name: Test

on: 
  workflow_dispatch:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - id: detect-type
        uses: DevExpress/testcafe-build-system/actions/release-lock@main
        with: 
          lock: ${{ secrets.RELEASE_LOCK }}
        