name: Test

on: 
  workflow_dispatch:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: DevExpress/testcafe-build-system/actions/detect-pr-title@main