name: Test

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - id: detect
        uses: ./actions/detect-build-scripts

      - run: "echo ${{ toJSON(steps.detect.outputs.scripts) }}"