name: Test

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - id: detect
        uses: ./actions/detect-build-scripts

      - run: "echo ${{ steps.detect.outputs.scripts[0] }}"