name: Test

on: 
  workflow_dispatch:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - id: detect-type
        uses: DevExpress/testcafe-build-system/actions/detect-pr-type@main
      - shell: bash
        env:
          TBS_PR_TYPE: ${{ steps.detect-type.outputs.type }}
        run: echo "$TBS_PR_TYPE"
        